import schedule
from crawler_code import csrc, local_csrc, neeq, sac, amac, \
    cbrc, local_cbrc, circ, local_circ, pbc, local_pbc, nafmii, cicpa, sse, szse
from lawyer_crawler import acla, ahlawyer, gdlawyer, gslawyer, gxlawyer, gzsls, hainanlawyer, hljls, hnlx, lnlawyers, \
    sdlawyer, shlawyers, sxlawyer, sxlsw, szlawyers, xblaw, zjbar
from finance_crawler import ahczt, bjccgp, cqczt, fjczt, gdczt, gsczt, gxczt, gzczt, hebcz, hljczt, hnczt, hunanczt, \
    jsczt, jxczt, nmgp, qdczj, scczt, sdczt, shczj, sxczt, szczt, xjczt, xmczj, ynczt, zjczt
from parser_code import amac_parse, cbrc_parse, circ_parse, csrc_parse, exchange_parse, local_csrc_parse, \
    nafmii_parse, neeq_parse, pbc_parse, sac_parse, sse_parse, szse_parse, finance_website_parse, lawyers_website_parse
from init import logger_init
import time
from datetime import datetime

logger = logger_init('总数据抓取解析')
cbrc_city_list = [
    '北京', '天津', '河北', '山西',
    '内蒙古', '辽宁', '吉林', '黑龙江',
    '上海', '江苏', '浙江', '安徽',
    '福建', '江西', '山东', '河南',
    '湖北', '湖南', '广东', '广西',
    '海南', '重庆', '四川', '贵州',
    '云南', '西藏', '甘肃', '陕西',
    '青海', '宁夏', '新疆', '深圳',
    '大连', '宁波', '厦门', '青岛'
]


def crawler_job():
    start_time = datetime.now()
    logger.info('开始时间：%s' % str(start_time))

    logger.info('开始抓取证监会数据......')
    csrc.csrc_crawler()
    time.sleep(30)
    logger.info('开始抓取地方证监局数据......')
    local_csrc.local_csrc_crawler()
    time.sleep(30)
    logger.info('开始抓取深交所数据......')
    szse.szse_crawler()
    time.sleep(30)
    logger.info('开始抓取上交所数据......')
    sse.sse_crawler()
    time.sleep(30)
    logger.info('开始抓取全国中小企业股份转让系统数据......')
    neeq.neeq_crawler()
    time.sleep(30)
    logger.info('开始抓取中国证券业协会数据......')
    sac.sac_crawler()
    time.sleep(30)
    logger.info('开始抓取中国基金业协会数据......')
    amac.amac_crawler()
    time.sleep(30)
    # logger.info('开始抓取地方银监局数据......')
    # for each_cbrc_city in cbrc_city_list:
    #     local_cbrc.local_cbrc(each_cbrc_city)
    #     time.sleep(10)
    # time.sleep(30)
    # logger.info('开始抓取中国银监会及派出机构数据......')
    # cbrc.cbrc_crawler()
    # cbrc.cbrc_crawler_yjj()
    # cbrc.cbrc_crawler_yjfj()
    # time.sleep(30)
    logger.info('开始抓取地方保监局数据......')
    local_circ.local_circ_crawler()
    time.sleep(30)
    logger.info('开始抓取保监会数据......')
    circ.circ_bjhcf_crawler()
    circ.circ_bjjcf_crawler()
    circ.circ_jgh_crawler()
    time.sleep(30)
    logger.info('开始抓取中国人民银行数据......')
    pbc.pbc()
    time.sleep(30)
    logger.info('开始抓取地方人民银行数据......')
    local_pbc.local_pbc_crawler()
    time.sleep(30)
    logger.info('开始抓取交易商协会数据......')
    nafmii.nafmii_crawler()
    time.sleep(30)

    logger.info('开始抓取注册会计师协会数据......')
    cicpa.cicpa_crawler()
    time.sleep(30)
    logger.info('开始抓取全国律师协会数据......')
    acla.acla_crawler()
    time.sleep(30)
    logger.info('开始抓取辽宁省律协数据......')
    lnlawyers.lnlawyers_crawler()
    time.sleep(30)
    logger.info('开始抓取湖南省律协数据......')
    hnlx.hnlx_crawler()
    time.sleep(30)
    logger.info('开始抓取浙江省律协数据......')
    zjbar.zjbar_crawler()
    time.sleep(30)
    # logger.info('开始抓取山西省律协数据......')
    # sxlsw.sxlsw_crawler()
    # time.sleep(30)
    logger.info('开始抓取广西自治区律协数据......')
    gxlawyer.gxlawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取黑龙江省律协数据......')
    hljls.hljls_crawler()
    time.sleep(30)
    logger.info('开始抓取安徽省律协数据......')
    ahlawyer.ahlawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取重庆市律协数据......')
    xblaw.xblaw_crawler()
    time.sleep(30)
    logger.info('开始抓取上海市律协数据......')
    shlawyers.shlawyers_crawler()
    time.sleep(30)
    logger.info('开始抓取山东省律师协会数据......')
    sdlawyer.sdlawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取甘肃省律师协会数据......')
    gslawyer.gslawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取陕西省律协数据......')
    sxlawyer.sxlawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取贵州省律师协会数据......')
    gzsls.gzsls_crawler()
    time.sleep(30)
    logger.info('开始抓取深圳市律协数据......')
    szlawyers.szlawyers_crawler()
    time.sleep(30)
    logger.info('开始抓取海南省律协数据......')
    hainanlawyer.hainanlawyer_crawler()
    time.sleep(30)
    logger.info('开始抓取广东省律师协会数据......')
    gdlawyer.gdlawyer_crawler()
    time.sleep(30)

    logger.info('开始抓取安徽省财政厅数据......')
    ahczt.ahczt_crawler()
    time.sleep(30)
    logger.info('开始抓取北京市财政局数据......')
    bjccgp.bjccgp_crawler()
    time.sleep(30)
    logger.info('开始抓取重庆市财政局数据......')
    cqczt.cqczj_crawler()
    time.sleep(30)
    logger.info('开始抓取福建省财政厅数据......')
    fjczt.fjczt_crawler()
    time.sleep(30)
    logger.info('开始抓取广东省财政厅数据......')
    gdczt.gdczt_crawler()
    time.sleep(30)
    logger.info('开始抓取甘肃省财政厅数据......')
    gsczt.gsczt_crawler()
    time.sleep(30)
    logger.info('开始抓取广西省财政厅数据......')
    gxczt.gxczt_crawler()
    time.sleep(30)
    logger.info('开始抓取贵州省财政厅数据......')
    gzczt.gzczt_crawler()
    time.sleep(30)
    logger.info('开始抓取河北省财政厅数据......')
    hebcz.hebcz_crawler()
    time.sleep(30)
    logger.info('开始抓取黑龙江省财政厅数据......')
    hljczt.hljczt_crawler()
    time.sleep(30)
    logger.info('开始抓取河南省财政厅数据......')
    hnczt.hnczt_crawler()
    time.sleep(30)
    logger.info('开始抓取湖南省财政厅数据......')
    hunanczt.hunanczt_crawler()
    time.sleep(30)
    logger.info('开始抓取江苏省财政厅数据......')
    jsczt.jiangsuczt_crawler()
    time.sleep(30)
    logger.info('开始抓取江西省财政厅数据......')
    jxczt.jxczt_crawler()
    time.sleep(30)
    logger.info('开始抓取内蒙古自治区财政厅数据......')
    nmgp.nmgczt_crawler()
    time.sleep(30)
    logger.info('开始抓取青岛市财政局数据......')
    qdczj.qdczj_crawler()
    time.sleep(30)
    logger.info('开始抓取四川省财政厅数据......')
    scczt.scczt_crawler()
    time.sleep(30)
    logger.info('开始抓取山东省财政厅数据......')
    sdczt.sdczt_crawler()
    time.sleep(30)
    logger.info('开始抓取上海市财政局数据......')
    shczj.shczj_crawler()
    time.sleep(30)
    logger.info('开始抓取山西省财政厅数据......')
    sxczt.sxsczt_crawler()
    time.sleep(30)
    logger.info('开始抓取深圳市财政局数据......')
    szczt.szczt_crawler()
    time.sleep(30)
    logger.info('开始抓取新疆维吾尔自治区财政厅数据......')
    xjczt.xjczt_crawler()
    time.sleep(30)
    logger.info('开始抓取厦门市财政局数据......')
    xmczj.xmczj_crawler()
    time.sleep(30)
    logger.info('开始抓取云南省财政厅数据......')
    ynczt.ynczt_crawler()
    time.sleep(30)
    logger.info('开始抓取浙江省财政厅数据......')
    zjczt.zjczt_crawler()
    time.sleep(30)

    end_time = datetime.now()
    logger.info('结束时间：%s' % str(end_time))
    logger.info('总共用时：%s' % str(end_time - start_time))


def parser_job():
    start_time = datetime.now()
    logger.info('开始时间：%s' % str(start_time))

    logger.info('开始解析上交所数据......')
    sse_parse.parse()
    time.sleep(30)
    logger.info('开始解析深交所数据......')
    szse_parse.parse()
    time.sleep(30)
    # logger.info('开始解析外管局数据......')
    # exchange_parse.parse()
    # time.sleep(30)
    logger.info('开始解析证监会数据......')
    csrc_parse.parse()
    time.sleep(30)
    logger.info('开始解析地方证监局数据......')
    local_csrc_parse.parse()
    time.sleep(30)
    logger.info('开始解析全国中小企业股份转让系统数据......')
    neeq_parse.parse()
    time.sleep(30)
    logger.info('开始解析中国证券业协会数据......')
    sac_parse.parse()
    time.sleep(30)
    logger.info('开始解析中国基金业协会数据......')
    amac_parse.parse()
    time.sleep(30)
    # logger.info('开始解析银监机构数据......')
    # cbrc_parse.parse()
    # time.sleep(30)
    logger.info('开始解析保监机构数据......')
    circ_parse.parse()
    time.sleep(30)
    logger.info('开始解析中国人民银行数据......')
    pbc_parse.parse()
    time.sleep(30)
    logger.info('开始解析交易商协会数据......')
    nafmii_parse.parse()
    time.sleep(30)
    logger.info('开始解析财政部门数据......')
    finance_website_parse.parse_all()
    time.sleep(30)
    logger.info('开始解析律协部门数据......')
    lawyers_website_parse.parse_all()

    end_time = datetime.now()
    logger.info('结束时间：%s' % str(end_time))
    logger.info('总共用时：%s' % str(end_time - start_time))


# 每次启动的时候就跑一遍
crawler_job()
# parser_job()
# 每天1：30开始抓取数据
schedule.every().day.at("01:30").do(crawler_job)
# 每周三早上6点开始解析数据，每周五早上6点开始解析数据
# schedule.every().wednesday.at("06:00").do(parser_job)
# schedule.every().friday.at("06:00").do(parser_job)

while True:
    schedule.run_pending()
    time.sleep(1)
